logging:
  level:
    org.springframework.web: DEBUG
    com.enjogu: DEBUG

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate